config/routes.rb
CRMRor::Application.routes.draw do
  get "passwd/newpasswd"

  put "passwd/updatepasswd"

  resources :statistics

  resources :client_posts


  resources :cl_comments


  resources :ppo_logs

  resources :mng_logs


  resources :gid2names


  resources :maps


  resources :zakazis


  resources :ttmsfiles


  resources :ttmscomments


  resources :ttms

  get 'tasks/change/:id' => 'tasks#change', as: 'task_change'
#  get 'tasks/change/:id(.:format)', to: 'tasks#change', as: 'task_change'
#  match 'tasks/change/' => 'tasks#change'
  resources :tasks

  get 'services/stop/:id' => 'services#stop_service', as: 'stop_service'
#  get 'services/stop/:id(.:format)', to: 'services#stop_service', as: 'stop_service'
  get 'services/start/:id' => 'services#start_service', as: 'start_service'
  get 'services/ping/:id' => 'services#ping_service', as: 'ping_service'
  get 'services/destroy/:id(.:format)', to: 'services#destroy_service', as: 'destroy_service'
  get 'services/remove_speed/:id(.:format)', to: 'services#remove_speed', as: 'remove_speed'
  get 'services/set_speed/:id(.:format)', to: 'services#set_speed', as: 'set_speed'
  resources :services


  resources :ports


  resources :erpfiles


  resources :devices


  resources :comments
 
  get 'main/' => 'reports#index'
  get 'reports/pporep/' => 'reports#pporep'
  get 'reports/wifipporep/' => 'reports#wifipporep'
  get 'reports/installrep/' => 'reports#installrep'
  get 'reports/newclient/' => 'reports#newclient'
  get 'reports/newzakaz/' => 'reports#newzakaz'
  get 'reports/services/' => 'reports#services'
  get 'reports/ttms/' => 'reports#ttms'
  get 'reports/genrep/' => 'reports#genrep'
  get 'reports/ttmsrep/' => 'reports#ttmsrep'
  get 'reports/spec_ttmsrep/' => 'reports#spec_ttmsrep'
  get 'reports/dogimrep/' => 'reports#dogimrep'
  get 'reports/profitlistrep/' => 'reports#profitlistrep'
  get 'reports/freephones/' => 'reports#freephones'
  get 'reports/typeconnect/' => 'reports#typeconnect'
  get 'reports/rastorgenie/' => 'reports#rastorgenie'
  get 'reports/wifiweek/' => 'reports#wifiweek'
  get 'reports/closeakt/' => 'reports#closeakt'
  get 'reports/dhcp_update/' => 'reports#dhcp_update'
  resources :reports



  get 'clients/list/' => 'clients#index'
  get 'clients/exists/' => 'clients#list_exists'
  get 'client/:id/tasks' => 'clients#tasks', as: 'client_tasks'
#  get 'client/:id/tasks(.:format)', to: 'clients#tasks', as: 'client_tasks'
  get 'client/:id/client_notification' => 'clients#client_notification'
  resources :clients

#  root to: "maps#index"
  root to: "clients#index"

end

app/helpers/services_helper.rb
# -*- encoding : utf-8 -*-
module ServicesHelper
  def srv_type_hash
    Hash['nat','NAT, серые IP',
         'inet','Интернет',
         'one-ip','IP из пула',
         'vlan','VLAN',
         'inet6','IPv6',
         'pool','Net-Pool',
         'vols','ВОЛС',
         'voip','VoIP',
         'phone','Телефон',
         'lm-wifi','LM-WiFi',
		 'ipunnam','IP-Unnambered',
		 'routable','Маршрутизация']
  end

  def srv_city_hash
    Hash['Ростов-на-Дону','Ростов-на-Дону',
         'Батайск','Батайск',
         'Азов','Азов',
         'Аксай','Аксай',
         'хут.Ленина','хут.Ленина']
  end

  def equipment_ports_array(type_s="inet")
    ports = case type_s
              when /phone/
                Port.joins("LEFT JOIN device on ports.iddev=device.id").where("device.type='vgw'").select("device.nic as nic,ports.port as port,ports.label as label,ports.idport as idport")
              else
                Port.joins("LEFT JOIN device on ports.iddev=device.id").select("device.nic as nic,ports.port as port,ports.label as label,ports.idport as idport").order(:nic,:port)
#                Port.order(:nic,:port)
            end    
    ar = ports.all.collect {|row| ["#{row.nic}, p-#{row.port} (#{row.label})",row.idport] }
    ar.unshift([nil,nil])
  end

  def get_ipnet_voip(mask)
    get_net( %w[172.16.0.], Service.where("type_s='voip'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }, mask)
  end

  def get_ip4net(mask)
#    get_net( %w[62.76.94.], Service.where("type_s='inet' OR type_s='one-ip' OR type_s='pool' OR type_s='routable' OR type_s='ipunnam'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }, mask)
    get_net( %w[195.208.36. 194.226.109. 194.226.129. 62.76.94. 212.192.202. 92.241.15. 92.241.17.], Service.where("type_s='inet' OR type_s='one-ip' OR type_s='pool' OR type_s='routable' OR type_s='ipunnam'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }, mask)
	end

  def get_nat_pool(mask)
    pools_templ = []
    0.upto(255) {|i| pools_templ.push("10.1.#{i}.") }
    get_net( pools_templ, Service.where("type_s='nat'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }, mask)
  end

  def get_net(pools_templ,exists_ip,mask)
    new_ip = nil
    ip_prefix = nil
    found_flag = true
    pools_templ.each do |ip_pat|
      0.step(255,2**(32-mask)) do |net_pat|
         new_ip = IPAddr.new(ip_pat+net_pat.to_s+"/"+mask.to_s)
         ip_prefix = ip_pat+net_pat.to_s+"/"+mask.to_s
         found_flag = false
         exists_ip.each {|ip| break if found_flag = (ip.include?(new_ip) || new_ip.include?(ip)) }
         break unless found_flag
      end
      break unless found_flag
    end
    found_flag ? nil : ip_prefix
  end

  def get_all_ip4net(mask)
    list_ip = %w[195.208.36. 194.226.109. 194.226.129. 62.76.94. 212.192.202. 92.241.15. 92.241.17. 194.190.110.]
    exists_ip = Service.where("type_s='inet' OR type_s='one-ip' OR type_s='pool' OR type_s='routable' OR type_s='ipunnam'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }
    new_ip = nil
    ip_prefix = nil
    found_flag = true
    free = []
    list_ip.each do |ip_pat|
      0.step(255,2**(32-mask)) do |net_pat|
        new_ip = IPAddr.new(ip_pat+net_pat.to_s+"/"+mask.to_s)
        ip_prefix = ip_pat+net_pat.to_s+"/"+mask.to_s
        found_flag = false
        exists_ip.each {|ip| break if found_flag = (ip.include?(new_ip) || new_ip.include?(ip)) }
        free.push(ip_prefix) unless found_flag
      end
    end
    free
  end

  def get_ip6net
    list_ip = %w[2001:67C:2B88::/48]
    exists_ip = Service.where(type_s: 'inet6').select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }
    new_ip = nil
    ip_prefix = nil
    found_flag = true
    list_ip.each do |ip_pat|
      IPAddr.new(ip_pat).to_i.step(IPAddr.new(ip_pat).to_range.last.to_i,(1<<64)) do |next_ip|
         new_ip = IPAddr.new(next_ip,Socket::AF_INET6).mask(64)
         return(new_ip.to_s<<"/64") unless exists_ip.include?(new_ip)
      end
    end
    nil
  end

  def get_one_ip(from_pool)
    pool_list = Service.where(type_s: 'ipunnam', cl_id: from_pool).select("vlan,ipaddr")
    exists_ip = Service.where("type_s='inet' AND ipaddr LIKE '%/32%' OR type_s='one-ip'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }
    new_ip = nil
    ip_prefix = nil
    found_flag = true
    pool_list.each do |pool|
      net = pool.ipaddr
      mma = /(\d+\.\d+\.\d+\.)(\d+)\/(\d+)/.match(pool.ipaddr)
      (ip_pat, fip, mask_len) = [mma[1],mma[2].to_i+2,mma[3].to_i]
      fip.step(fip+(2**(32-mask_len))-4,1) do |net_pat|
         new_ip = IPAddr.new(ip_pat+net_pat.to_s)
logger.debug "pool=#{pool} #{new_ip} #{net}"
         return([new_ip,get_free_vlan(""),net]) unless exists_ip.include?(new_ip)
      end
    end
    [nil,nil,nil]
  end

  def get_ipunnambered(from_pools)
#      from_pools = ["62.76.94."]
	if from_pools.empty? 
		from_pools = Service.where("pool like '%/24'").select("pool,count(pool) as cc").group(:pool).order(:cc).map {|p| /(\d+\.\d+\.\d+\.)(\d+)\/(\d+)/.match(p.pool)[1] } 
	end
    exists_ip = Service.where("type_s in ('inet', 'one-ip', 'ipunnam', 'routable')").where("ipaddr LIKE '"+from_pools.join("%' OR ipaddr LIKE '")+"%'").select("ipaddr").collect {|s| IPAddr.new(s.ipaddr.gsub(/\s/,'')) }
    new_ip = nil
    ip_prefix = nil
    found_flag = true
	vlan = get_free_vlan('ipunnam')
    from_pools.each do |pool|
		post_fix = pool=='185.102.138.' ? "0/25" : "0/24"
		2.upto(254) do |net_pat|
			new_ip = IPAddr.new(pool+net_pat.to_s)
			found_flag = false
			exists_ip.each {|ip| break if found_flag = (ip.include?(new_ip) || new_ip.include?(ip)) }
			return([pool+net_pat.to_s,vlan,pool+post_fix]) unless found_flag
		end
    end
    nil
  end



  def get_free_vlan(type_s)
    exists_vlan = case (type_s)
                    when 'nat'
                      Service.where("vlan>300 AND vlan<1200")
                    else
                      Service.where("vlan>101 AND vlan<900 OR vlan>999")
                    end
    exists_vlan = exists_vlan.select("vlan").group("vlan").order("vlan").collect {|s| s.vlan}
#    logger.debug exists_vlan.inspect
    vlan=0 
    if type_s == 'nat'
      if exists_vlan.empty?
        vlan = 900
      else
        900.upto(exists_vlan[-1]+1) do |v|
          vlan=v
          break unless exists_vlan.include?(vlan)
        end
      end
    else
      102.upto(exists_vlan[-1]+1) do |v|
         vlan=v
         break unless exists_vlan.include?(vlan)
      end
    end
    vlan
  end

#-------------------------------------------------------------------

  def get_free_phone
    TypePhoneNumber.joins("LEFT JOIN services ON type_phone_numbers.phone=services.ipaddr").where("serv_id is NULL AND type_p='обычный'").select("phone").first.phone
  end
  def get_free_phones
    TypePhoneNumber.joins("LEFT JOIN services ON type_phone_numbers.phone=services.ipaddr").where("serv_id is NULL").select("phone,type_p").order("type_p,phone")
  end

  def datalist_free_phones
    res= "<datalist id=free_phones>\n"
    get_free_phones.each { |row|  res << "<option value='" << row.phone << " - " << row.type_p << "'>\n" }
    res << "</datalist>\n"
  end

#-------------------------------------------------------------------
	def get_snmp_speed(addr,port)
		begin
			manager = SNMP::Manager.new(:Host => addr, :Community =>'DiDi-RO', :Version => :SNMPv1)
			sp = manager.get_value("1.3.6.1.4.1.8886.6.1.2.2.1.3.#{port}")
			sp=~/^\d*$/ ? sp : 0
		rescue 
			0
		end
	end
#------------------------------------------------------------

  def device_port_show_speed(service)
#	if service.cl_port =~ /^sw/
#		ps = get_snmp_speed(service.device_ip,service.device_port)
#		if service.speed.to_i != ps.to_i
#			"#{service.speed} <font size=1>(#{ps})</font>".html_safe
#		else
#			service.speed
#		end
#	else
#		service.speed
#	end
	service.speed
  end
  
#------------------------------------------------------------
	def show_router_helper(service)
		gw={'195.208.36.190'=>'<a href=telnet://10.61.0.1>Red</a> -> ', '194.190.110.94'=>'<a href=http://10.61.0.26>White</a> ->'}
		case service.type_s
		when /nat|inet6/
			'<a href=http://10.61.0.26/>White</a> ->'.html_safe
#	when /^inet$|one-ip/
#			gw[`ssh -l admin 10.61.0.235 /ip route check dst-ip=212.192.202.196 once|grep nexthop|awk '{print $2}'`.chomp].html_safe
		else
			""
		end
	end
#------------------------------------------------------------
	def get_interface_ipunnam(pool)
		hh = {'185.102.138.0/25' => 'GigabitEthernet0/2.221',
				'194.226.109.0/24' => 'GigabitEthernet0/2.239',
				'194.226.129.0/24' => 'Gi0/2.753',
				'195.208.36.0/24' => 'Gi0/2.151',
				'62.76.94.0/24' => 'Gi0/2.184',
				'92.241.15.0/24' => 'Gi0/2.130',
				'92.241.17.0/24' => 'Gi0/2.136'
				}
		hh[pool]
	end

end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<img src=/images/item.gif border=0>
<table border=0>
  <tr>
    <td class=hblist>Тип</td>
    <td class=hblist>Город</td>
    <td class=hblist>Адрес</td>
   <% if @service.type_s=='phone' %>
    <td class=hblist>Кол-во линий</td>
    <td class=hblist>Номера</td>
   <% else %>
    <td class=hblist>Скорость</td>
    <td class=hblist>VLAN ID</td>
    <td class=hblist>IP addr</td>
  <% end %>
    <td class=hblist colspan=2>Порт оборудования</td>
  </tr>
<tr>
<td> <%= f.select(:type_s, srv_type_hash.keys.collect {|key| [srv_type_hash[key],key]}) %></td>
<td><%= f.select(:city, srv_city_hash.keys.collect {|key| [srv_city_hash[key],key]}) %></td>
   <%=datalist_addr.html_safe %>
<td><%=f.text_field :addr, :list => 'addr'%></td>
<td><%=f.text_field :speed, :size=>7 %></td>
 <% 
if not @service.type_s == 'phone' %>
   <td><%=f.text_field :vlan, :size=>7 %></td>
 <% end %>
<td class=slist>
 <% if @service.type_s == 'phone' %>
   <%=datalist_free_phones.html_safe %>
   <%= f.text_field :ipaddr, :list => 'free_phones' %>
 <% else %>
   <%= f.text_field :ipaddr, :size=>15 %>
 <% end %>
  <% if @service.type_s == 'one-ip' || @service.type_s == 'ipunnam' || @service.type_s == 'routable' %>
    <br><%= f.text_field :pool, :size=>15 %>
  <% end %>
</td>
<td class=small><%=f.select(:port_id, equipment_ports_array(@service.type_s), { style: "font-family : verdana; font-size : 6pt; width: 140px"})%></td>
<td><%= f.submit 'Enter', class: "slist" %></td>
</tr>
</table>
<%= hidden_field_tag :cl_id, params[:cl_id] %>
<% end %>

app/views/services/destroy_service.tcl.erb
tclsh
ios_config "no interface gi0/2.<%= @service.vlan %>" 
ios_config "no ip route <%= @service.ipaddr %> 255.255.255.255 GigabitEthernet0/2.<%= @service.vlan %>"
write memory

app/views/services/edit.html.erb
<h1>Редактирование сервиса</h1>

<%= render 'form' %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>
<table width=100%><td><%= will_paginate @services %></td><td>
<%= form_tag services_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= hidden_field_tag :cl_id, params[:cl_id] %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Найти", :name => nil %>
<% end %>
</td><td>
Добавить:
<%= link_to 'IP-unnam', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "ipunnam") %> / 
<%= link_to 'NAT, серые IP', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "nat") %> / 
<%= link_to 'Интернет', new_service_path(cl_id: params[:cl_id]) %> / 
<%= link_to 'IP из пула', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "one-ip") %> / 
<%= link_to 'VLAN', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "vlan") %> /
<%= link_to 'IPv6', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "inet6") %> /
<%= link_to 'ВОЛС', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "vols") %> /
<%= link_to 'VoIP', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "voip") %> /
<%= link_to 'Телефон', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "phone") %> /
<%= link_to 'LM-WiFi', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "lm-wifi") %> /
<%= link_to 'POOL', new_service_path(cl_id: @client.flag =='DD' ? 71 : 413,"service[type_s]"=> "pool") %> 
</td></table>
<table width=100%>
  <tr>
    <td class=hblist><%= sortable "type_s", "Тип",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
    <td class=hblist><%= sortable "city", "Город",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
    <td class=hblist><%= sortable "addr", "Адрес",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
    <td class=hblist><%= sortable "speed", "Скорость",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
    <td class=hblist><%= sortable "vlan", "VLAN ID",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
    <td class=hblist><%= sortable "ipaddr", "IP addr",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
    <td class=hblist colspan=2><%= sortable "port_id", "Порт оборудования",{:search=>params[:search], :cl_id=> params[:cl_id]}%></td>
  </tr>

<% @services.each do |service| %>
  <tr class="<%= service.status=="start" ? cycle(:sclist, :dclist) : "reedlist" %>">
    <td><%= service.type_s %></td>
    <td><%= service.city %></td>
    <td><%= service.addr %></td>
    <td><%= device_port_show_speed(service) %></td>
    <td><%= service.vlan %></td>
    <td><%= if service.type_s == 'one-ip'
				link_to_function service.ipaddr, "ping_service(#{service.id})"
			else
				service.ipaddr 
			end	%>
	    <div id="div_ping_loss_<%=service.id%>"></div>
	   </td>
	<% 
	host = CactiHost.where(hostname: service.device_ip)
	graphs = host.empty? ? [] : host[0].cacti_graph.where(snmp_index: service.device_port )
	local_graph_id = graphs.empty? ? nil : graphs[0].id  
	port_label = service.port_label.nil? ? "port-"+service.device_port.to_s : service.port_label
#		local_graph_id = nil
 %>

    <td>
	     <!-- % = show_router_helper(service)% -->
	     <div class="divwhite">
<!-- = !service.port.nil? && !service.port.device.nil? && !service.port.device.perc.nil? && service.port.device.perc > 50 ? "divred" : "divwhite" % > -->
	      <%= local_graph_id.nil? ? service.cl_port : link_to(service.device_nic,"telnet://#{service.device_ip}") +" " + link_to(port_label, "http://192.168.5.102/graph.php?action=view&rra_id=all&local_graph_id=#{local_graph_id}" ) %>
	    </div>
&nbsp;
<!--        <div class=<= !service.port.nil? && service.port.status == 0 ? "divred" : "divwhite" >><= !service.port.nil? && service.port.status == 1 ? "UP" : "DOWN" ></div>  -->
         <%= link_to tag("img", { :src => "/images/button_edit.gif", :alt => "Edit"}, false),"/services/#{service.serv_id}/edit?cl_id=#{params[:cl_id]}"%>
         <%= link_to tag("img", {  :src => "/images/button_drop.gif", :alt => "Del"}, false), "/services/#{service.serv_id}?cl_id=#{params[:cl_id]}".html_safe, method: :delete, data: { confirm: 'Are you sure?' } %>
     &nbsp;
   <%=  if service.status=="start"
          link_to tag("img", {  :src => "/images/stop.gif", :alt => "Stop"}, false), stop_service_path(service.serv_id,"service[status]"=>"stop"), data: { confirm: 'Are you sure?' }
       else
         link_to tag("img", {  :src => "/images/start.gif", :alt => "Start"}, false), start_service_path(service.serv_id,"service[status]"=>"start"), data: { confirm: 'Are you sure?' }
       end
    %>
    </td>
  </tr>
<% end %>
</table>

<% if !@services_phone.empty? %>
<p>
<table width=70%>
  <tr>
    <td class=hblist><%= sortable "type_s", "Тип"%></td>
    <td class=hblist><%= sortable "city", "Город"%></td>
    <td class=hblist><%= sortable "addr", "Адрес"%></td>
    <td class=hblist><%= sortable "speed", "Кол-во линий"%></td>
    <td class=hblist><%= sortable "ipaddr", "Номера"%></td>
    <td class=hblist colspan=2><%= sortable "port_id", "Порт оборудования"%></td>
  </tr>

<% @services_phone.each do |service| %>
  <tr class="<%= cycle :sclist, :dclist %>">
    <td><%= service.type_s %></td>
    <td><%= service.city %></td>
    <td><%= service.addr %></td>
    <td align=center><%= service.speed %></td>
    <td align=center><%= service.ipaddr %></td>
	
    <td>
         <%= link_to tag("img", { :src => "/images/button_edit.gif", :alt => "Edit"}, false),"/services/#{service.serv_id}/edit?cl_id=#{params[:cl_id]}"%>
         <%= link_to tag("img", {  :src => "/images/button_drop.gif", :alt => "Del"}, false), "/services/#{service.serv_id}?cl_id=#{params[:cl_id]}".html_safe, method: :delete, data: { confirm: 'Are you sure?' } %>
     &nbsp;
   <%  if service.status=="start"
         link_to tag("img", {  :src => "/images/stop.gif", :alt => "Stop"}, false), services_path, data: { confirm: 'Are you sure?' }
       else
         link_to tag("img", {  :src => "/images/start.gif", :alt => "Start"}, false), services_path, data: { confirm: 'Are you sure?' }
       end
    %>
    </td>
  </tr>
<% end %>
</table>
<% end %>

app/views/services/new.html.erb
<h1>Добавить сервис</h1>

<%= render 'form' %>

app/views/services/show-OLD.tcl.erb
configure terminal
interface gi0/2.<%= @service.vlan %>
 encapsulation dot1Q <%= @service.vlan %>
 ip unnumbered GigabitEthernet0/2.221
 ip helper-address 194.190.110.245
 no ip redirects
 rate-limit input <%= @service.speed.to_i * 1000 %> <%= (@service.speed.to_i * 187.5).to_i %> <%= (@service.speed.to_i * 187.5 * 2).to_i %> conform-action transmit exceed-action drop
 rate-limit output <%= @service.speed.to_i * 1000 %> <%= (@service.speed.to_i * 187.5).to_i %> <%= (@service.speed.to_i * 187.5 * 2).to_i %> conform-action transmit exceed-action drop
 no cdp enable
exit
ip route <%= @service.ipaddr %> 255.255.255.255 GigabitEthernet0/2.<%= @service.vlan %>
end
write memory

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Serv:</b>
  <%= @service.serv_id %>
</p>

<p>
  <b>Cl:</b>
  <%= @service.cl_id %>
</p>

<p>
  <b>Type:</b>
  <%= @service.type_s %>
</p>

<p>
  <b>Addr:</b>
  <%= @service.addr %>
</p>

<p>
  <b>City:</b>
  <%= @service.city %>
</p>

<p>
  <b>Speed:</b>
  <%= @service.speed %>
</p>

<p>
  <b>Vlan:</b>
  <%= @service.vlan %>
</p>

<p>
  <b>Ipaddr:</b>
  <%= @service.ipaddr %>
</p>

<p>
  <b>Port:</b>
  <%= @service.port_id %>
</p>

<p>
  <b>Status:</b>
  <%= @service.status %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/services/show.tcl.erb
tclsh
<% if @service.type_s == 'ipunnam' %>
ios_config "interface gi0/2.<%= @service.vlan %>" "encapsulation dot1Q <%= @service.vlan %>" "ip unnumbered <%= get_interface_ipunnam(@service.pool)%>" "ip helper-address 194.190.110.245"  "no ip redirects"
ios_config "interface gi0/2.<%= @service.vlan %>" "rate-limit input <%= @service.speed.to_i * 1000 %> <%= (@service.speed.to_i * 1000 * 1.5 / 8).to_i %> <%= @service.speed.to_i * 1000 * 2 / 8 %> conform-action transmit exceed-action drop" 
ios_config "interface gi0/2.<%= @service.vlan %>" "rate-limit output <%= @service.speed.to_i * 1000 %> <%= (@service.speed.to_i * 1000 * 1.5 / 8).to_i %> <%= @service.speed.to_i * 1000 * 2 / 8 %> conform-action transmit exceed-action drop"
ios_config "ip route <%= @service.ipaddr %> 255.255.255.255 GigabitEthernet0/2.<%= @service.vlan %>"
<% elsif @service.type_s == 'nat' %>
ios_config "interface gi0/2.<%= @service.vlan %>" "encapsulation dot1Q <%= @service.vlan %>" "ip address <%= IPAddr.new((IPAddr.new serv.ipaddr.chomp).to_i+1,Socket::AF_INET).to_s %> <%= (IPAddr.new serv.ipaddr.chomp).inspect.split(/[\/>]/)[1]%>" "ip helper-address 194.190.110.245"  "no ip redirects" "rate-limit input <%= @service.speed.to_i * 1000 %> <%= (@service.speed.to_i * 1000 * 1.5 / 8).to_i %> <%= @service.speed.to_i * 1000 * 2 / 8 %> conform-action transmit exceed-action drop" "rate-limit output <%= @service.speed.to_i * 1000 %> <%= (@service.speed.to_i * 1000 * 1.5 / 8).to_i %> <%= @service.speed.to_i * 1000 * 2 / 8 %> conform-action transmit exceed-action drop"
<% elsif @service.type_s == 'inet6' %>
ios_config "interface gi0/2.<%= @service.vlan %>" "encapsulation dot1Q <%= @service.vlan %>" "ipv6 address <%= @service.ipaddr.chomp %>/64"
<% end %>
write memory