config/routes.rb
CRMRor::Application.routes.draw do
  get "passwd/newpasswd"

  put "passwd/updatepasswd"

  resources :statistics

  resources :client_posts


  resources :cl_comments


  resources :ppo_logs

  resources :mng_logs


  resources :gid2names


  resources :maps


  resources :zakazis


  resources :ttmsfiles


  resources :ttmscomments


  resources :ttms

  get 'tasks/change/:id' => 'tasks#change', as: 'task_change'
#  get 'tasks/change/:id(.:format)', to: 'tasks#change', as: 'task_change'
#  match 'tasks/change/' => 'tasks#change'
  resources :tasks

  get 'services/stop/:id' => 'services#stop_service', as: 'stop_service'
#  get 'services/stop/:id(.:format)', to: 'services#stop_service', as: 'stop_service'
  get 'services/start/:id' => 'services#start_service', as: 'start_service'
  get 'services/ping/:id' => 'services#ping_service', as: 'ping_service'
  get 'services/destroy/:id(.:format)', to: 'services#destroy_service', as: 'destroy_service'
  get 'services/remove_speed/:id(.:format)', to: 'services#remove_speed', as: 'remove_speed'
  get 'services/set_speed/:id(.:format)', to: 'services#set_speed', as: 'set_speed'
  resources :services


  resources :ports


  resources :erpfiles


  resources :devices


  resources :comments
 
  get 'main/' => 'reports#index'
  get 'reports/pporep/' => 'reports#pporep'
  get 'reports/wifipporep/' => 'reports#wifipporep'
  get 'reports/installrep/' => 'reports#installrep'
  get 'reports/newclient/' => 'reports#newclient'
  get 'reports/newzakaz/' => 'reports#newzakaz'
  get 'reports/services/' => 'reports#services'
  get 'reports/ttms/' => 'reports#ttms'
  get 'reports/genrep/' => 'reports#genrep'
  get 'reports/ttmsrep/' => 'reports#ttmsrep'
  get 'reports/spec_ttmsrep/' => 'reports#spec_ttmsrep'
  get 'reports/dogimrep/' => 'reports#dogimrep'
  get 'reports/profitlistrep/' => 'reports#profitlistrep'
  get 'reports/freephones/' => 'reports#freephones'
  get 'reports/typeconnect/' => 'reports#typeconnect'
  get 'reports/rastorgenie/' => 'reports#rastorgenie'
  get 'reports/wifiweek/' => 'reports#wifiweek'
  get 'reports/closeakt/' => 'reports#closeakt'
  get 'reports/dhcp_update/' => 'reports#dhcp_update'
  resources :reports



  get 'clients/list/' => 'clients#index'
  get 'clients/exists/' => 'clients#list_exists'
  get 'client/:id/tasks' => 'clients#tasks', as: 'client_tasks'
#  get 'client/:id/tasks(.:format)', to: 'clients#tasks', as: 'client_tasks'
  get 'client/:id/client_notification' => 'clients#client_notification'
  resources :clients

#  root to: "maps#index"
  root to: "clients#index"

end

app/models/task.rb
# -*- encoding : utf-8 -*-
class Task < ActiveRecord::Base
    ActiveRecord::Base.send :include, TasksHelper

  after_create :ins_log
  after_update :upd_log
  after_destroy :del_log
  before_update :set_task_close, :if => :status_changed?

  self.table_name = "task"
  attr_accessible :autor, :cl_id, :dead_line, :zapros_gid, :from_userid, :idtask, :name, :result, :status, :target, :time_change, :time_create, :time_from, :time_to, :to_gid, :to_userid, :type_t, :point_group, :flag, :type_s, :dogovor_num, :dogovor_date, :res1_date, :res2_date, :ppo_income, :dogim, :task_close
  has_many :comments, :foreign_key => "idtask"
  has_many :erpfiles, :foreign_key => "idtask"
  belongs_to :client, :foreign_key => 'cl_id'
  belongs_to :auth, :foreign_key => 'autor'
  belongs_to :from_user, :foreign_key => 'from_userid', class_name: "Auth"
  validates :ppo_income, numericality: true, :if => :type_task_ppomap?
  
  validate :check_client_time_work, :on => :update, message: "Необходимо указывать время работы клиента"
  
  geocoded_by :name
  after_validation :geocode


  def type_task_ppomap?
    type_t =~ /ppomap/
  end

  def self.search(search)
    if search
      where('task.name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def current_staff=(id)
    @current_staff=id
  end


  protected
   def ins_log
     if self.status == 'end' and self.type_t =~ /pay/
       t = self.dup
       t.type_t = if type_s == 'Телефония'
                     "shem"
                  else
                     self.type_t =~ /wifi/ ? "wifiinstall" : "install"
                  end
       t.time_create = Time.now.getlocal
       t.status = "new"
       t.save
     end
     MngLog.create(cr_time: Time.now.getlocal, who: @current_staff.fullname+" ("+@current_staff.user+")", text: task_action_parser(self.client,self,"create"))
     Mailer.email_addtask(@current_staff,self.client,self).deliver
   end
#===============================================================
   def upd_log
     if self.status == 'end' and self.type_t =~ /pay/ && ! Task.exists?(cl_id: self.cl_id, point_group: self.point_group, zapros_gid: self.zapros_gid, type_t: ["install","wifiinstall"])
       t = self.dup
       t.type_t = if type_s == 'Телефония'
                    "shem"
                  else
                    self.type_t =~ /wifi/ ? "wifiinstall" : "install"
                  end
       t.time_create = Time.now.getlocal
       t.status = "new"
       t.save
     end
   end
   
#===============================================================   
   def set_task_close
     if self.status == 'end'
       self.task_close = Time.now.getlocal 
       self.from_userid = @current_staff.id unless @current_staff.nil?
     end
   end
   def del_log
   end
#===============================================================      
	def check_client_time_work
	
	logger.debug "Check time"
	logger.debug self.type_t
	logger.debug self.client.time_work.inspect
	logger.debug self.client.time_work.length > 9
		if self.type_t == 'zakaz' && self.status!='end2'
			if self.client.time_work.length < 9
				errors.add(:status, "Необходимо указывать время работы клиента")
			end
			if self.client.email.nil? || self.client.email.empty? || self.client.email_tech.nil? || self.client.email_tech.empty? || self.client.contact.nil? || self.client.contact.empty? || self.client.contact_tech.nil?
				errors.add(:status, "Необходимо указывать телефоны и email клиента")
			end
			if self.client.inn.nil? 
				errors.add(:status, "Необходимо указывать ИНН клиента")
			end
		else
			true
		end
	end
end

app/helpers/tasks_helper.rb
# -*- encoding : utf-8 -*-
module TasksHelper
 def task_type_hash
   Hash['ppomap','ППО-карта',
     'ppoobj','ППО-объект',
     'sogl','Согласование', 
     'zakaz','Договор', 
     'pay','Оплата', 
     'nopay','Без оплаты', 
     'shem','Схема', 
     'install','Инсталляция ВОЛС', 
     'install1','Инсталляция Сервиса',
     'akt','Подписание АКТа',
     'wifippomap','ППО-карта WiFi',
     'wifippoobj','ППО-объект WiFI',
     'wifisogl','Согласование WiFi',
     'wifizakaz','Договор WiFi',
     'wifipay','Оплата WiFi',
     'wifinopay','WiFi Без оплаты',
     'wifiinstall','Инсталляция WiFi',
     'wifiakt','Подписание АКТа WiFi',
     'voice','Телефония',
	 'arenda','Аренда',
	 'upgrade','Модернизация',
	 'test-voip','Телефон на тест'
     ]
 end

 def deadline(type)
   t = Time.now
   tr = case(type)
     when 'ppomap'
       t.wday==5 ? t+86400*3 : t+86400
     when 'ppoobj'
       t.wday>2 ? t+86400*6 : t+86400*3
     when 'sogl'
       t+86400*14
     when 'zakaz'
       t.wday==5 ? t+86400*3 : t+86400
     when 'pay'
       t.wday==5 ? t+86400*3 : t+86400
     when 'shem'
       t.wday==5 ? t+86400*3 : t+86400
     when /install|akt/
       t+86400*14
     when 'voice'
       t.wday==5 ? t+86400*3 : t+86400
   end
   tr.strftime("%Y-%m-%d")
 end

 def task_status_hash
   Hash['new',"Новая",
        'run',"Выполняется",
        'end0',"Завершены_лин_раб",
        'end',"Выполнена",
        'stop',"Приостановлен",
        'clsogl',"На согласовании у клиента",
        'end1',"Расторжение",
        'end2',"Расторгнут",
        'nopay',"Без оплаты"]
 end

 def task_vols_status_hash
   Hash['new',"Новая",
        'run',"Выполняется",
        'end0',"Завершены_лин_раб",
        'end',"Завершена_сварка"]
 end

 def task_srv_type_hash
   Hash["Интернет","Интернет",
        "VLAN","VLAN",
        "Аренда ВОК","Аренда ВОК",
        "Покупка ВОК","Покупка ВОК",
        'Телефония','Телефония']
 end

 def task_wifi_srv_type_hash
   Hash["Интернет","Интернет",
        "VLAN","VLAN" ]
 end

 def task_status_bgcolor(status)
   case(status)
     when /new|end1/
        "red"
     when 'run'
        "green"
     else
        "white"
   end
 end

 def dd_check_permit(staff,action,type_t,client)
logger.debug "staff=" << staff.inspect
logger.debug "staff.groups=" << staff.groupid.inspect
logger.debug "action=" << action
logger.debug "type_t=#{type_t}"
logger.debug "client.flag=#{client.flag}"
logger.debug "----------------------------"
    if !staff.admin?
      case action
        when /index|show/
               if staff.groupid.include?(11)
                 true
               elsif staff.groupid.include?(6) && client.flag=='DD' || staff.groupid.include?(3) && client.flag=='DT'
                 false
               else
                 true
               end
######################
				true
######################				
        when /new|create|change/
           case type_t
             when /ppo|sogl|zakaz|pay|akt|voice|test-voip/
               if staff.groupid.include?(3) || staff.groupid.include?(6) #  Отдел продаж
                 true
               else
                 false
               end
             when /shem|install/
                 true
			when /arenda|upgrade/
				true
             else
               false
           end
        when /update|edit/
          case type_t
             when /ppomap|voice|arenda|test-voip/
               true
             when /ppoobj|sogl|shem/
               if staff.groupid.include?(7) || staff.groupid.include?(4) #  Магистраль
                 true
               else
                 false
               end
             when 'install'
               if staff.groupid.include?(7) #  Магистраль
                 true
               else
                 false
               end
             when /install1|upgrade/
               if staff.groupid.include?(8) #  Магистраль
                 true
               else
                 false
               end
             when /zakaz|akt/
               if staff.groupid.include?(3) || staff.groupid.include?(6) #  Отдел продаж
                 true
               else
                 false
               end
             when /pay/
               if staff.groupid.include?(5) || staff.groupid.include?(12) #  Отдел продаж
                 true
               else
                 false
               end
             else
               false
           end
        when /destroy/
          task=Task.find(params[:id])
          if task.status=="new" && task.autor==@staff_login.id
            true
          else
            false
          end
        else
          false
      end
    else
      true
    end
 end

#======================================================================================================
 def dt_check_permit(staff,action,type_t,client)
logger.debug "staff=" << staff.inspect
logger.debug "staff.groups=" << staff.groupid.inspect
logger.debug "action=" << action
logger.debug "type_t=#{type_t}"
logger.debug "client.flag=#{client.flag}"
logger.debug "----------------------------"
    if !staff.admin?
      case action
        when /index|show/
               if staff.groupid.include?(6) && client.flag=='DD' || staff.groupid.include?(3) && client.flag=='DT' || staff.groupid.include?(11) && client.flag=='DT'
                 false
               else
                 true
               end
        when /new|create/
           case type_t
             when /ppo|sogl|zakaz|pay|shem|install|akt|voice/
               if staff.groupid.include?(6) || staff.groupid.include?(3)   #  Отдел продаж
                 true
               else
                 false
               end
             when /install/
                 true
             else
               false
           end
        when /update|edit/
          case type_t
             when /ppo|sogl/
               true
             when /shem|install/
               if staff.groupid.include?(9) ||  staff.groupid.include?(10)  #  Технический отдел
                 true
               else
                 false
               end
             when /zakaz|akt|voice/
               if staff.groupid.include?(6) || staff.groupid.include?(3) #  Отдел продаж
                 true
               else
                 false
               end
             when /pay/
               if staff.groupid.include?(5) || staff.groupid.include?(12) #  Отдел продаж
                  true
               else
                  false
               end
             else
               false
           end
        when /destroy/
          task=Task.find(params[:id])
          if task.status=="new" && task.autor==@staff_login.id
            true
          else
            false
          end
        else
          false
      end
    else
      true
    end
####################
true
####################
	
 end
#====================================================================================
  def default_user_task
    case @staff_login.id
      when 91
        "shem"
      when 133,141,130
        "install1"
      else
        "ppomap"
    end
  end

  def authorize
    req1 = params[:task]
    req2 = req1.nil? ? params : req1
    type_t = !params[:id].nil? && req2["type_t"].nil? ? Task.find(params[:id]).type_t : req2["type_t"]
    client = Client.find(params[:cl_id])
    res= if req2["type_t"] =~ /^wifi/
           dt_check_permit(@staff_login,params["action"],type_t,client)
         else
           dd_check_permit(@staff_login,params["action"],type_t,client)
         end
    redirect_to clients_path, flash: { error: "Недостаточно прав" } unless res
    res
  end
#====================================================================================
  def dd_reglament_button(task,type_t)
    case type_t
          when 'ppomap'
            ( Task.where(point_group: task.point_group, type_t: "ppoobj", cl_id: task.cl_id).count==0 ? link_to(tag("img", { :src => "/images/home.png", :title =>'ППО Объект',:border=>0}, false), new_task_path(cl_id: params[:cl_id], type_t:"ppoobj", point_group: task.point_group)) : "".html_safe )
          when 'ppoobj'
            if task.status=='end'
              (if task.flag=~/sogl/
               (Task.where(point_group: task.point_group, type_t: "sogl", cl_id: task.cl_id).count==0 ? link_to(tag("img", { :src => "/images/clipboard.png", :title =>'Согласование',:border=>0}, false), new_task_path(:cl_id=>params[:cl_id],:type_t=>"sogl")<<"&point_group=#{task.point_group}") : "".html_safe) << "&nbsp;".html_safe
              else
                (Task.where(point_group: task.point_group, type_t: "zakaz", cl_id: task.cl_id).count==0 ? link_to( tag("img", { :src => "/images/zakaz.png", :title =>'Договор',:border=>0}, false), new_task_path(:cl_id=>params[:cl_id],:type_t=>"zakaz")<<"&point_group=#{task.point_group}") : "".html_safe)
              end) +  link_to( tag("img", { :src => "/images/reload.png", :title =>'Перезапустить задачу',:border=>0 }, false), task_change_path(:id=>task.id, "task[status]"=> "new", :cl_id=>task.cl_id))
            elsif task.status=='stop'
              link_to tag("img", { :src => "/images/start.gif", :title => 'Возобновить',:border=>0}, false), task_change_path(task,:task=>{:status=>"new",:type_t=>"ppoobj"},cl_id: task.cl_id)
            else
              link_to tag("img", { :src => "/images/stop.gif", :title => 'Отложить',:border=>0}, false), task_change_path(task,:task=>{:status=>"stop",:type_t=>"ppoobj"}, cl_id: task.cl_id)
            end
          when 'sogl'
            if task.status=='end'
              (Task.where(point_group: task.point_group, type_t: "zakaz", cl_id: task.cl_id).count==0 ? link_to(tag("img", { :src => "/images/zakaz.png", :title =>'Договор',:border=>0}, false), new_task_path(:cl_id=>params[:cl_id],:type_t=>"zakaz")<<"&point_group=#{task.point_group}") : "".html_safe) << "&nbsp;".html_safe
            elsif task.status=='new' || task.status=='run'

app/views/tasks/edit.html.erb
<h4>Editing task</h4>

<%= render 'form' %>

app/views/tasks/index.html.erb
  <% if flash[:error] %>
    <div id="error_explanation">
      <ul><li><%= flash[:error] %></li></ul>
    </div>
  <% end %>
<table width=80%><td><%= will_paginate @task %></td>
<td><%= link_to "Кратко", ppo_logs_path(cl_id: params[:cl_id]) %></td>
<td>
<%= form_tag tasks_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= hidden_field_tag :cl_id, params[:cl_id] %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Найти", :name => nil %>
<% end %>
</td><td>Добавить 
<%= link_to 'ППО-карту', new_task_path(cl_id: params[:cl_id], type_t: default_user_task) %> / 
<%= link_to 'ППО-карту WiFi', new_task_path(cl_id: params[:cl_id], type_t: 'wifippomap') %> / 
<%= link_to 'Схему', new_task_path(cl_id: params[:cl_id], type_t: 'shem') if @staff_login.groupid.include?(4) %> / 
<%= link_to 'Телефония', new_task_path(cl_id: params[:cl_id], type_t: 'voice', type_s: 'Телефония') %> /
<%= link_to 'Аренда', new_task_path(cl_id: params[:cl_id], type_t: 'arenda', type_s: 'Аренда') %>
</td></table>

<p>
<%= render 'task_group' %>
<p>
<%= will_paginate @task %>

app/views/tasks/new.html.erb
<h2>Добавить задачу</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
  <% if flash[:error] %>
    <div id="error_explanation">
      <ul><li><%= flash[:error] %></li></ul>
    </div>
  <% end %>
      <table ><tr><td width=70%>
        <table class=tab1>
          <tr>
            <td class=tab1_td1>Тип задачи</td>
            <td><%= task_type_hash[@task.type_t]%></td>
          </tr>
          <tr>
            <td class=tab1_td1>Адрес</td>
            <td><%=@task.name%></td>
          </tr>
          <tr>
            <td class=tab1_td1><%= @task.type_s=~/Телефония/ ? "Количество линий" : "Скорость" %></td>
            <td>
     <%= form_for(@task) do |f| %>
            <%= @task.type_t=~/zakaz/ ? f.text_field(:target) : @task.target %>
            </td>
          </tr>
          <tr>
            <td class=tab1_td1>Тип сервиса</td>
            <td><%=@task.type_s.nil? ? "Интернет" : @task.type_s%></td>
          </tr>
          <tr>
            <td class=tab1_td1>Выполнить до</td>
            <td><%=@task.dead_line%></td>
          </tr>
          <tr>
            <td class=tab1_td1>Предпологаемый доход</td>
            <td><%= f.text_field :ppo_income %> руб.</td>
          </tr>
          <tr>
          <td class=tab1_td1>Лист дожима</td><td><%= f.check_box :dogim, {}, "yes"%></td>
          </tr>

          <tr>
            <td class=tab1_td1>Статус</td>
            <td>
          <%= 
                if @task.type_t =~ /ppo|sogl|pay|install/ && (@staff_login.groupid.include?(3) || @staff_login.groupid.include?(6))
                  if @task.type_t=='install'
                    task_vols_status_hash[@task.status]
                  else
                    task_status_hash[@task.status]
                  end
                else
                  if @task.type_t=='install'
                    f.select(:status, task_vols_status_hash.keys.collect {|key| [task_vols_status_hash[key],key]})
                  else
                    f.select(:status, task_status_hash.keys.collect {|key| [task_status_hash[key],key]})
                  end
                end
             %>
           <%= if @task.status=='end' && !@task.task_close.nil?
                 "#{@task.from_user.surname unless @task.from_user.nil?} " + @task.task_close.strftime("%F")
               elsif @task.status=='end'
                 "#{@task.from_user.surname unless @task.from_user.nil?} " + @task.time_create.strftime("%F")
               end
             %> 
            </td>
          </tr>
       <% if @task.type_t=~/zakaz/ %>
         <tr>
           <td class=tab1_td1>Номер договора</td>
           <td><%= f.text_field :dogovor_num %>
           </td>
         </tr>
         <tr>
           <td class=tab1_td1>Дата договора</td>
           <td><input type=date name="task[dogovor_date]" id=dogovordate value=<%=@task.dogovor_date%>>
           </td>
         </tr>
         <tr>
           <td class=tab1_td1>Ежемесячный платеж</td>
           <td><%= f.text_field :flag %>
           </td>
         </tr>
       <% end %>
       <% if @task.type_t=~/arenda/ %>
          <tr>
           <td class=tab1_td1>Ежемесячный платеж</td>
           <td><%= f.text_field :flag %>
           </td>
         </tr>
       <% end %>

       <% if @task.type_t=='install' %>
         <tr><td class=tab1_td1>Планируемый срок "Магистраль"</td><td><input type=date name="task[res1_date]" id=res1date value=<%=@task.res1_date%>></td></tr>
         <tr><td class=tab1_td1>Планируемый срок "Сварка"</td><td><input type=date name="task[res2_date]" id=res2date value=<%=@task.res2_date%>></td></tr>
       <% end %>
       <% if @task.type_t=='install1' || @task.type_t=='wifiinstall' %>
         <tr><td class=tab1_td1>Планируемый срок "Сервис"</td><td><input type=date name="task[res1_date]" id=res1date value=<%=@task.res1_date%>></td></tr>
       <% end %>
         <tr>
       <% if @task.type_t=~/pay/ %>
<!--     
          <td class=tab1_td1>Дата платежa</td>
           <td>
            <input type=date name="task[res1_date]" id=result value=<%=@task.res1_date%> ></td>
         </tr> -->
         <tr>
           <td class=tab1_td1>Сумма платежа</td>
           <td>
            <%= f.text_field :result %>
       <% else %>
           <td class=tab1_td1><%= @task.type_t=~/zakaz|arenda/ ? "Инсталляционный платеж" : "Результат"%></td>
           <td>
            <%= f.text_field :result %>
       <% end %>
            <%= f.submit 'Сохранить изменение'%>&nbsp;
            <%= hidden_field_tag "task[cl_id]", params[:cl_id] %>
            <%= hidden_field_tag "task[type_t]", @task.type_t %>
            <%= hidden_field_tag "cl_id", params[:cl_id] %>
           </td>
         </tr>
        <% if @task.type_t=~/ppoobj/ %>
         <tr>
           <td class=tab1_td1>Требуются согласования</td>
           <td><input type=checkbox name=task[flag] value="sogl" <%="checked" if @task.flag=~/sogl/%>>
           </td>
         </tr>
        <% end %>
     <% end %>
           </td>
         </tr>

        </table>
      </td><td rowspan=2 valign=top width=30%>
        <table>
    <% if @task.type_t=='install1' %>
Добавить:
<%= link_to 'Интернет', new_service_path(cl_id: params[:cl_id],"service[speed]"=>@task.target,"service[addr]"=>@task.name) %> /
<%= link_to 'IP из пула', new_service_path(cl_id: params[:cl_id],"service[type_s]"=>"one-ip","service[speed]"=>@task.target,"service[addr]"=>@task.name) %> /
<%= link_to 'VLAN', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "vlan","service[speed]"=>@task.target,"service[addr]"=>@task.name) %> /
<%= link_to 'IPv6', new_service_path(cl_id: params[:cl_id],"service[type_s]"=> "inet6","service[speed]"=>@task.target,"service[addr]"=>@task.name) %>

    <% end %>
        <tr><td>
          <a class=menu1 href=# onclick="divattache.style.display='';">
    <%= tag("img",{:src=>"/images/button_attache.png", :title=>"Прикрепить", :border=>0}, false)%>
           </a>
          <div id=divattache style="display:none;">     
            <div id="upload-form">
      <%= form_for(@erpfile) do |f| %>
           <%= hidden_field_tag "erpfile[do]", "upload" %>
           <%= hidden_field_tag "erpfile[idtask]", @task.id %>
           <%= hidden_field_tag "erpfile[userid]", @staff_login.id %>
           <%= hidden_field_tag "erpfile[groupid]", @staff_login.groupid.min %>
           <%= hidden_field_tag :cl_id, params[:cl_id] %>
           <%= hidden_field_tag "sessid" %>
              File:
              <%= f.file_field :file, :size=>40 %>
              <p>
              <%= f.submit "Upload It!" %><p>
      <% end %>
          </div>
        </td></tr>
        <%
          if @erpfiles.count > 0
          %>
            <tr><td>
              <div style="margin-left:5%;"><div class=td1>Файлы:</div><br>
            </td></tr>
        <%
            @erpfiles.each do |erpfile|
          %>
            <tr><td class=tab3_td_white>
        <%
              if erpfile.status=='new'
          %>
               <%= link_to erpfile.name, erpfile_path(erpfile) %>
               <%= link_to tag("img",{:src=>"/images/button_drop.gif", :title=>"Удалить",:border=>0},false), erpfile_path(erpfile,cl_id: params[:cl_id]), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%
              else
          %>
              <del><%= erpfile.name%></del>
        <%
              end
          %>
           <br>*** <b><%= erpfile.auth.surname unless erpfile.auth.nil?%></b> <%= erpfile.time.getlocal.strftime("%Y-%m-%d %H:%M")%>
           </td></tr>
         <%
            end
          end
          %>
        </table>
      </td></tr>
      <tr><td>
        <table class=tab1 style="background-color:#cadaba;">
           <tr>
             <td class=tab1_td1>Комментарий:<br>
                  <%= form_for(@comment) do |f| %>
                       <%= f.text_area :text, cols: 70, rows: 7%>
                       <%= hidden_field_tag "comment[idtask]", @task.id %>
                       <%= hidden_field_tag :cl_id, params[:cl_id] %>
                      <%= f.submit 'Добавить коммент'%>
                  <% end %>
              </td>
           </tr>

            <tr>
              <td class=tab1_td1>Список сообщений:</td>
            </tr>
      <%
        @comments.each do |comm|
        %>
        <tr><td><%=comm.text.html_safe%><br>*** <b><%= comm.auth.surname unless comm.auth.nil? %></b>&nbsp;<%=comm.time.getlocal.strftime("%Y-%m-%d %H:%M") unless comm.time.nil? %></td></tr>
      <%
        end
        %>
         </table>
      </td><td></td></tr>

      </table>
<%= link_to 'Edit', edit_task_path(@task,cl_id: params[:cl_id]) if @staff_login.admin? %>