config/routes.rb
CRMRor::Application.routes.draw do
  get "passwd/newpasswd"

  put "passwd/updatepasswd"

  resources :statistics

  resources :client_posts


  resources :cl_comments


  resources :ppo_logs

  resources :mng_logs


  resources :gid2names


  resources :maps


  resources :zakazis


  resources :ttmsfiles


  resources :ttmscomments


  resources :ttms

  get 'tasks/change/:id' => 'tasks#change', as: 'task_change'
#  get 'tasks/change/:id(.:format)', to: 'tasks#change', as: 'task_change'
#  match 'tasks/change/' => 'tasks#change'
  resources :tasks

  get 'services/stop/:id' => 'services#stop_service', as: 'stop_service'
#  get 'services/stop/:id(.:format)', to: 'services#stop_service', as: 'stop_service'
  get 'services/start/:id' => 'services#start_service', as: 'start_service'
  get 'services/ping/:id' => 'services#ping_service', as: 'ping_service'
  get 'services/destroy/:id(.:format)', to: 'services#destroy_service', as: 'destroy_service'
  get 'services/remove_speed/:id(.:format)', to: 'services#remove_speed', as: 'remove_speed'
  get 'services/set_speed/:id(.:format)', to: 'services#set_speed', as: 'set_speed'
  resources :services


  resources :ports


  resources :erpfiles


  resources :devices


  resources :comments
 
  get 'main/' => 'reports#index'
  get 'reports/pporep/' => 'reports#pporep'
  get 'reports/wifipporep/' => 'reports#wifipporep'
  get 'reports/installrep/' => 'reports#installrep'
  get 'reports/newclient/' => 'reports#newclient'
  get 'reports/newzakaz/' => 'reports#newzakaz'
  get 'reports/services/' => 'reports#services'
  get 'reports/ttms/' => 'reports#ttms'
  get 'reports/genrep/' => 'reports#genrep'
  get 'reports/ttmsrep/' => 'reports#ttmsrep'
  get 'reports/spec_ttmsrep/' => 'reports#spec_ttmsrep'
  get 'reports/dogimrep/' => 'reports#dogimrep'
  get 'reports/profitlistrep/' => 'reports#profitlistrep'
  get 'reports/freephones/' => 'reports#freephones'
  get 'reports/typeconnect/' => 'reports#typeconnect'
  get 'reports/rastorgenie/' => 'reports#rastorgenie'
  get 'reports/wifiweek/' => 'reports#wifiweek'
  get 'reports/closeakt/' => 'reports#closeakt'
  get 'reports/dhcp_update/' => 'reports#dhcp_update'
  resources :reports



  get 'clients/list/' => 'clients#index'
  get 'clients/exists/' => 'clients#list_exists'
  get 'client/:id/tasks' => 'clients#tasks', as: 'client_tasks'
#  get 'client/:id/tasks(.:format)', to: 'clients#tasks', as: 'client_tasks'
  get 'client/:id/client_notification' => 'clients#client_notification'
  resources :clients

#  root to: "maps#index"
  root to: "clients#index"

end

app/models/statistic.rb
class Statistic < ActiveRecord::Base

  attr_accessible :id, :week, :staff_id, :created_at, :updated_at, :otdel, :s1,:s2,:s3,:s4,:s5,:s6,:s7,:s8,:s9,:s10,:s11,:s12

  belongs_to :auth, :foreign_key => 'staff_id'
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  include ClientsHelper

  def index
    @stats = Statistic.where(otdel: params[:otdel])
    @newstat = Statistic.new(otdel: params[:otdel], week: ( Date.today-Date.today.cwday + 1))
    
    if params[:otdel] == 'marketing'
      @stats = {}
      (Date.today-Date.today.cwday + 1 - 7*30).step(Date.today,7) { |d| 
        @stats[d] = {:arr => GenRep.where(type_t: "zakaz",status:'end').where("task_close>=? AND task_close<=?",d,d+6).joins("left join clients on genrep.cl_id=clients.cl_id").where("not clients.cl_src='manager'") }
#        @stats[d][:all] = Client.where("date_add >= ? AND date_add<= ?",d,d+6).count
         @stats[d][:all] =  Client.where("date_add >= ? AND date_add<= ?",d,d+6).count(:group => :cl_src)
      }
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stats }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @stat = Statistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @stat = Statistic.new(params[:statistic])
    cur_week = Date.today
    cur_week -= (cur_week.wday + 6).days
    @stat.week = cur_week 

    @stat.staff_id = @staff_login.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stat }
    end
  end

  # GET /comments/1/edit
  def edit
    @stat = Statistic.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @stat = Statistic.new(params[:statistic])
    @stat.staff_id = @staff_login.id

    respond_to do |format|
      if @stat.save
        mnglog = MngLog.new(cr_time: Time.now.getlocal, who: @staff_login.fullname+" ("+@staff_login.user+")", text: params[:statistic].inspect)
        mnglog.save
        format.html { redirect_to statistics_path(otdel: params[:statistic][:otdel]), notice: 'Add statistic' }
        format.json { render json: statistics_path, status: :created, location: @stat }
      else
        format.html { render action: "new" }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @stat = Statistic.find(params[:id])

    respond_to do |format|
      if @stat.update_attributes(params[:statistic])
        format.html { redirect_to statistics_path(otdel: params[:statistic][:otdel]), notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @stat = Statistic.find(params[:id])
    @stat.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url(otdel: params[:otdel]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/statistics_helper.rb
# -*- encoding : utf-8 -*-
module StatisticsHelper
  def stat_name_hash
     Hash['sales',Hash[
                       'новых кп','Кол-во новых контактов КП',
                       'новые звонки','Кол-во новых контактов звонки',
                       'встречи','Встречи',
                       'контрактов в разработке','Кол-во контрактов в разработке',
                       'реестре запросов','Кол-во клиентов в реестре запросов',
                       'расторжения','Расторжения за неделю',
                       'подписанных договоров','Количество подписанных договоров за отчетный период',
                       'процент - план','Выполнение плана %',
                       'ПРОФИТ-лист кол-во','Динамика ПРОФИТ-листа по отношению к предыдущей неделе кол-во', 
                       'ПРОФИТ-лист сумма','Динамика ПРОФИТ-листа по отношению к предыдущей неделе сумма'
                       ],
          'vols',Hash['новых м','Кол-во новых м',
                      'сварок','Кол-во завершенных сварок',
                      'включений','Количество включений',
                      'аварий','Количество аварий, время на их восстановление',
                      'муфт','Сварки муфт',
                      'кроссов','Сварки кроссов',
                      'построенных м','Количество построенных м за отчетный период',
                      'ППО-карта задолженностей','Обзор ППО-карта (сколько в настоящий момент задолженностей)',
                      'ППО-объект задолженностей','Обзор ППО-объект (сколько в настоящий момент задолженностей)' 
                      ],
          'service',Hash[
                        'инсталляций','Количество инсталляций',
                        'обращений','Количество обращений за период',
                        'сбоев в сети','Количество сбоев в сети',
                        'трафик ретн','Пики, потребление трафика RETN',
                        'трафик всд','Пики, потребление трафика ВСД',
                        'трафик ix','Пики, потребление трафика IX'
                       ],
          'buh',Hash['дебиторка за пред месяц','Дебиторская задолженность за предыдущий месяц',
                     'дебиторка за пред пред месяц','Дебиторская задолженность за предшествующий предыдущему месяц',
                     'дебиторка за весь период','Дебиторская задолженность за весь период' 
                     ],
          'marketing',Hash['заявки','Входящие заявки за отчетный период'
                    ]
         ]
  end

  def otdels_hash
    Hash['sales','Продажи',
         'vols','Технический отдел',
         'service','Отдел инсталляции',
         'buh','Отдел финансов',
         'marketing','Маркетинг'
    ]
  end

  def week_list_hash
    hh = Hash.new
    (Date.today-Date.today.cwday + 1 - 7*30).step(Date.today,7) { |d| hh[d] = d.strftime("%d.%m")+" - "+(d+4).strftime("%d.%m")}
    hh
  end
end

app/views/statistics/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :groupid %><br />
    <%= f.number_field :groupid %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :idtask %><br />
    <%= f.number_field :idtask %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/_index.html.erb
<h1>Listing </h1>

<table>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stats.each do |stat| %>
  <tr>
    <td><%= stat.id %></td>
    <td><%= stat.name %></td>
    <td><%= stat.score %></td>
    <td><%= stat.week %></td>
    <td><%= stat.auth.f_l_name %></td>
    <td><%= link_to 'Edit', edit_statistic_path(stat) %></td>
    <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stat', new_statistic_path %>

app/views/statistics/_service.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :id %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.select(:name , stat_name_hash[params[:statistic][:otdel]].keys.collect {|key| [stat_name_hash[params[:statistic][:otdel]][key],key] } )%>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :week %><br />
    <input type=date name="statistic[week]" id=stat_week value=<%=@stat.week%> >
  </div>
  <div class="field">
    <%= f.label :staff %><br />
    <%= f.select(:staff_id, Auth.select("firstname,surname,id").collect {|staff| ["#{staff.firstname} #{staff.surname}",staff.id] unless staff.firstname.empty?}.compact) %>
  </div>
  <div class="actions">
    <%= f.hidden_field :otdel %>
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/_services_index.html.erb
<table border=0 width=100% id="statistics" class="display"?
  <thead>
    <tr>
      <td class=hblist>Неделя</td>
      <% stat_name_hash[params[:otdel]].keys.each do |kk| %>
        <td class=hblist><%= kk %></td>
      <% end %>
      <td class=hblist>#</td>
    </tr>
  </thead>

  <tbody>

  <% @stats.each do |stat| %>
      <%= form_for(stat) do |f| %>
      <tr class="<%= cycle :sclist, :dclist %>">
        <td align=center><%= f.text_field :week, :onclick => "document.getElementById('submit#{stat.id}').style.display = '';", :size=>6 %></td>
        <% 1.upto(6) do |i| %>
          <td align=center><%= f.text_field "s#{i}", :onclick => "document.getElementById('submit#{stat.id}').style.display = '';", :size=>6 %></td>
        <% end %>
      <td>
       <%= link_to tag("img", {  :src => "/images/button_drop.gif", :alt => "Del"}, false), stat, method: :delete, data: { confirm: 'Are you sure?' } %>
       &nbsp;
       <%= f.submit "Save", :id => "submit#{stat.id}", :type => :image, :src => "/images/disk.png", style: 'display:none' %>
    </td>
    </tr>
    <% end %>
  <% end %>

      <%= form_for(@newstat) do |f| %>
          <tr class="<%= cycle :sclist, :dclist %>">
            <td align=center><%= f.text_field :week, :size=>6 %></td>
            <% 1.upto(6) do |i| %>
              <td align=center><%= f.text_field "s#{i}", :size=>6 %></td>
            <% end %>
        <td>
          <%= f.hidden_field :otdel %>
         <%= f.submit "Save", :id => "submitnewstat", :type => :image, :src => "/images/disk.png" %>
      </td>
      </tr>
      <% end %>

  <tbody>
</table>

app/views/statistics/_statistics_table_marketing.html.erb
<table border=1 width=100% id="statistics" class="display">
  <thead>
    <tr>
      <td class=hblist>Неделя</td>
      <td class=hblist>Источники</td>
    </tr>
  </thead>

  <tbody>
  <% logger.debug @stats.inspect %>
  <% @stats.keys.each do |week| 
     %>
      <tr class="<%= cycle :sclist, :dclist %>">
      <td align=center width=8%><%= week.strftime("%d.%m")+" - "+(week+4).strftime("%d.%m") %> </td>
      <td align=center>
        <% @stats[week][:arr].each do |kk| %>
          <%= link_to kk.name+', сумма='+ kk.tflag+', источник - '+ client_source_hash[kk.client.cl_src], task_path(kk.idtask,cl_id:kk.cl_id) %><br>
        <% end %>
        <table width=100%><tr>
           <% @stats[week][:all].keys.each do |src| %>
             <td class="endtd"><%= client_source_hash[src] %></td>
           <% end %>
         </tr>
         <tr>
           <% @stats[week][:all].keys.each do |src| %>
             <td class=""><%= @stats[week][:all][src] %></td>
           <% end %>
         </tr>
       </table>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/statistics/_statistics_table_template.html.erb
<table border=0 width=100% id="statistics" class="display"?
  <thead>
    <tr>
      <td class=hblist>Неделя</td>
      <% stat_name_hash[params[:otdel]].keys.each do |kk| %>
        <td class=hblist><%= kk %></td>
      <% end %>
      <td class=hblist>#</td>
    </tr>
  </thead>

  <tbody>

  <% @stats.each do |stat| %>
      <%= form_for(stat) do |f| %>
      <tr class="<%= cycle :sclist, :dclist %>">
        <td align=center><%= f.select(:week, week_list_hash.keys.collect {|key| [week_list_hash[key],key]}) %>
          </td>
        <% 1.upto(stat_name_hash[params[:otdel]].keys.length) do |i| %>
          <td align=center><%= f.text_field "s#{i}", :onclick => "document.getElementById('submit#{stat.id}').style.display = '';", :size=>6 %></td>
        <% end %>
      <td align=center>
       <%= link_to tag("img", {  :src => "/images/button_drop.gif", :alt => "Del"}, false), statistic_path(id: stat.id, otdel: stat.otdel) , method: :delete, data: { confirm: 'Are you sure?' } %>
       &nbsp;
       <%= f.submit "Save", :id => "submit#{stat.id}", :type => :image, :src => "/images/disk.png", style: 'display:none' %>
       <%= f.hidden_field :otdel %>
       </td>
    </tr>
    <% end %>
  <% end %>

      <%= form_for(@newstat) do |f| %>
          <tr class="<%= cycle :sclist, :dclist %>">
            <td align=center><%= f.select(:week, week_list_hash.keys.collect {|key| [week_list_hash[key],key]}) %></td>
            <% 1.upto(stat_name_hash[params[:otdel]].keys.length) do |i| %>
              <td align=center><%= f.text_field "s#{i}", :size=>6 %></td>
            <% end %>
        <td align=center>
          <%= f.hidden_field :otdel %>
         <%= f.submit "Save", :id => "submitnewstat", :type => :image, :src => "/images/disk.png" %>
      </td>
      </tr>
      <% end %>

  <tbody>
</table>

app/views/statistics/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/statistics/index.html.erb
 <% otdels_hash.keys.each do |otdel| %>
   <%= params[:otdel] == otdel ? "<b>#{otdels_hash[otdel]}</b>".html_safe : link_to(otdels_hash[otdel], statistics_path(otdel: otdel)) %>
 <% end %>
 <p>
 <%= if params[:otdel] == 'marketing'
       render "statistics_table_marketing"
     else
       render "statistics_table_template" unless params[:otdel].nil? 
     end
     %>

app/views/statistics/new.html.erb
<h1>New stat</h1>

<%= render params[:statistic][:otdel] %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @comment.userid %>
</p>

<p>
  <b>Groupid:</b>
  <%= @comment.groupid %>
</p>

<p>
  <b>Time:</b>
  <%= @comment.time %>
</p>

<p>
  <b>Text:</b>
  <%= @comment.text %>
</p>

<p>
  <b>Idtask:</b>
  <%= @comment.idtask %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>