config/routes.rb
CRMRor::Application.routes.draw do
  get "passwd/newpasswd"

  put "passwd/updatepasswd"

  resources :statistics

  resources :client_posts


  resources :cl_comments


  resources :ppo_logs

  resources :mng_logs


  resources :gid2names


  resources :maps


  resources :zakazis


  resources :ttmsfiles


  resources :ttmscomments


  resources :ttms

  get 'tasks/change/:id' => 'tasks#change', as: 'task_change'
#  get 'tasks/change/:id(.:format)', to: 'tasks#change', as: 'task_change'
#  match 'tasks/change/' => 'tasks#change'
  resources :tasks

  get 'services/stop/:id' => 'services#stop_service', as: 'stop_service'
#  get 'services/stop/:id(.:format)', to: 'services#stop_service', as: 'stop_service'
  get 'services/start/:id' => 'services#start_service', as: 'start_service'
  get 'services/ping/:id' => 'services#ping_service', as: 'ping_service'
  get 'services/destroy/:id(.:format)', to: 'services#destroy_service', as: 'destroy_service'
  get 'services/remove_speed/:id(.:format)', to: 'services#remove_speed', as: 'remove_speed'
  get 'services/set_speed/:id(.:format)', to: 'services#set_speed', as: 'set_speed'
  resources :services


  resources :ports


  resources :erpfiles


  resources :devices


  resources :comments
 
  get 'main/' => 'reports#index'
  get 'reports/pporep/' => 'reports#pporep'
  get 'reports/wifipporep/' => 'reports#wifipporep'
  get 'reports/installrep/' => 'reports#installrep'
  get 'reports/newclient/' => 'reports#newclient'
  get 'reports/newzakaz/' => 'reports#newzakaz'
  get 'reports/services/' => 'reports#services'
  get 'reports/ttms/' => 'reports#ttms'
  get 'reports/genrep/' => 'reports#genrep'
  get 'reports/ttmsrep/' => 'reports#ttmsrep'
  get 'reports/spec_ttmsrep/' => 'reports#spec_ttmsrep'
  get 'reports/dogimrep/' => 'reports#dogimrep'
  get 'reports/profitlistrep/' => 'reports#profitlistrep'
  get 'reports/freephones/' => 'reports#freephones'
  get 'reports/typeconnect/' => 'reports#typeconnect'
  get 'reports/rastorgenie/' => 'reports#rastorgenie'
  get 'reports/wifiweek/' => 'reports#wifiweek'
  get 'reports/closeakt/' => 'reports#closeakt'
  get 'reports/dhcp_update/' => 'reports#dhcp_update'
  resources :reports



  get 'clients/list/' => 'clients#index'
  get 'clients/exists/' => 'clients#list_exists'
  get 'client/:id/tasks' => 'clients#tasks', as: 'client_tasks'
#  get 'client/:id/tasks(.:format)', to: 'clients#tasks', as: 'client_tasks'
  get 'client/:id/client_notification' => 'clients#client_notification'
  resources :clients

#  root to: "maps#index"
  root to: "clients#index"

end

app/controllers/reports_controller.rb
# -*- encoding : utf-8 -*-
class ReportsController < ApplicationController
  include ReportsHelper
  include ApplicationHelper
  before_filter :authorize
  helper_method :sort_column, :sort_direction
  
  def show
    @rep_num = params[:id]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  def index
  end

  def pporep
    @pporep= if @staff_login.admin? || @staff_login.groupid.include?(2)
               PpoReport.where(filter_pporep).search(params[:search]).order(sort_column + " " + sort_direction)
             elsif @staff_login.groupid.include?(6)
               PpoReport.where("flag='DT'").search(params[:search]).order(sort_column + " " + sort_direction)
             elsif @staff_login.groupid.include?(3)
               PpoReport.where("flag='DD'").search(params[:search]).order(sort_column + " " + sort_direction)
             else
               PpoReport.where(filter_pporep).search(params[:search]).order(sort_column + " " + sort_direction)
             end
     if @staff_login.gr_names == ["Отдел продаж ЦД"]
       @pporep= case @staff_login.fullname
                when /Антропов|Долгин/
                  @pporep.where(manager: ['Антропов Константин','ИП Эндер'])
                when /Макарова/
                  @pporep.where(manager: ['Макарова Ирина','ООО "Медиа 161"','ИП Щербина','ИП Волчанская'])
                when /Ваганов/
                  @pporep.where(manager: ['Ваганов Андрей','ИП Адаменко','ИП Долгин','АК Спецсвязь'])
                when /Гученко/
                  @pporep.where(manager: ['Гученко Наталья','АК Спецсвязь','СТС'])
				else
				   @pporep
                end
     end

     @pporep= @pporep.where(manager: @staff_login.fullname) if @staff_login.gr_names == ["Отдел продаж ДТ"]

     @pporep= @pporep.where("flag=?",params[:flag]) if (not params[:flag].nil?) && (not params[:flag].empty?)
     @pporep= @pporep.where("type_t=?",params[:type_t]) if (not params[:type_t].nil?) && (not params[:type_t].empty?)
     @pporep= @pporep.where("type_t='ppomap'")
     @pporep= @pporep.paginate(:per_page => 28, :page => params[:page]) unless params[:pg]=="off"

  end

  def wifipporep
    @wifipporep= if @staff_login.groupid.include?(6)
               if params[:pg]=="off"
                 WifiPpoReport.where("flag='DT'").search(params[:search]).order(sort_column + " " + sort_direction)
               else
                 WifiPpoReport.where("flag='DT'").search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 28, :page => params[:page])
               end
              elsif @staff_login.groupid.include?(3)
               if params[:pg]=="off"
                 WifiPpoReport.where("flag='DD'").search(params[:search]).order(sort_column + " " + sort_direction)
               else
                 WifiPpoReport.where("flag='DD'").search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 28, :page => params[:page])
               end
              else
               if params[:pg]=="off"
                 WifiPpoReport.where(filter_pporep).search(params[:search]).order(sort_column + " " + sort_direction)
               else
                 WifiPpoReport.where(filter_pporep).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 28, :page => params[:page])
               end
             end
     @wifipporep= @wifipporep.where(manager: @staff_login.fullname) if @staff_login.gr_names == ["Отдел продаж ЦД"] || @staff_login.gr_names == ["Отдел продаж ДТ"]
     @wifipporep= @wifipporep.where("flag=?",params[:flag]) if (not params[:flag].nil?) && (not params[:flag].empty?)
     @wifipporep= @wifipporep.where("type_t=?",params[:type_t]) if (not params[:type_t].nil?) && (not params[:type_t].empty?)
     @wifipporep= @wifipporep.where("type_t='wifippomap'")
  end

  def installrep
    @installrep= PpoReport.select("cl_id,cl_name,t_name,manager,flag,target,income,type_t,type_s,cast(t1cr as date) as t1cr,cast(t1ch as date) as t1ch,t1s,t1r,cast(t2cr as date) as t2cr,cast(t2ch as date) as t2ch,t2s,t2r,cast(t3cr as date) as t3cr,cast(t3ch as date) as t3ch,t3s,t3r,cast(t4cr as date) as t4cr,cast(t4ch as date) as t4ch,t4s,t4r,t4dog_date,t4dog_num,t4_i_pay,t4_e_pay,cast(t5cr as date) as t5cr,cast(t5ch as date) as t5ch,t5s,t5r,cast(t5cl as date) as t5cl,cast(t6cr as date) as t6cr,cast(t6ch as date) as t6ch,t6s,t6r,cast(t7cr as date) as t7cr,cast(t7ch as date) as t7ch,t7s,t7r,t7res1date,t7res2date,cast(t8cr as date) as t8cr,cast(t8ch as date) as t8ch,t8s,t8r,t8res1date,cast(t9cr as date) as t9cr,cast(t9ch as date) as t9ch,t9s,t9r,flag1").where("(t4s='end' or t5s='end') and (isnull(t9s) or t9s='new' or t9s='run') AND (type_s='Интернет' OR type_s='Покупка ВОК' OR type_s='Аренда ВОК' OR type_s='VLAN' OR type_s='Телефония') AND t4s!='end1'")
    @installrep = @installrep.where(" not cl_id=15")
    @installrep= if @staff_login.groupid.include?(2) || @staff_login.admin?
                   @installrep
                 elsif @staff_login.groupid.include?(3) 
                   @installrep.where("flag='DD'")
                 elsif @staff_login.groupid.include?(6)
                   @installrep.where("flag='DT'")
                 else
                   @installrep
                 end
    if @staff_login.gr_names == ["Отдел продаж ЦД"]
      @installrep= case @staff_login.fullname
                   when /Антропов|Долгин/
                     @installrep.where(manager: ['Антропов Константин','ИП Эндер'])
#                   when /Макарова/
#                     @installrep.where(manager: ['Макарова Ирина','ООО "Медиа 161"','ИП Щербина','ИП Волчанская'])
                   when /Ваганов/
                     @installrep.where(manager: ['Ваганов Андрей','ИП Адаменко','ИП Долгин','АК Спецсвязь'])
                   when /Гученко/
                     @installrep.where(manager: ['Гученко Наталья','АК Спецсвязь','СТС'])
				   else
				     @installrep
                   end
    end
     @installrep= @installrep.where(manager: @staff_login.fullname) if @staff_login.gr_names == ["Отдел продаж ДТ"]
     @installrep= if params[:flag].nil? || params[:flag].empty?
                    @installrep
                  else
                    @installrep.where(flag: params[:flag])
                  end
     @installrep= case params[:type]
                  when 'ppomap'
                    @installrep.where("type_t='ppomap'")
                  when 'wifippomap'
                    @installrep.where("type_t='wifippomap'")
                  when 'voice'
                    @installrep.where("type_t='voice'")
                  else
                    @installrep
                  end
     @installrep= case params[:status]
                  when 'run'
                    @installrep.where("not t7s='end' or isnull(t7s) or not t8s='end' or isnull(t8s)")
                  when 'end'
                    @installrep.where("type_t='voice' AND t8s='end' OR t7s='end' and t8s='end'")
                  when 'end1'
                    @installrep.where("t9s='end'")
                  else
                    @installrep
                  end
     @installrep= @installrep.search(params[:search]).order(sort_column + " " + sort_direction)
     respond_to do |format|
       format.html
       format.xls
     end
  end

  def closeakt
    @d1 = params[:d1].nil? ? (Time.now - 3600*24*7).strftime("%Y-%m-%d") : params[:d1]
    @d2 = params[:d2].nil? ? Time.now.strftime("%Y-%m-%d") : params[:d2]
    @installrep= PpoReport.select("cl_id,cl_name,t_name,manager,flag,target,income,type_t,type_s,cast(t1cr as date) as t1cr,cast(t1ch as date) as t1ch,t1s,t1r,cast(t2cr as date) as t2cr,cast(t2ch as date) as t2ch,t2s,t2r,cast(t3cr as date) as t3cr,cast(t3ch as date) as t3ch,t3s,t3r,cast(t4cr as date) as t4cr,cast(t4ch as date) as t4ch,t4s,t4r,t4dog_date,t4dog_num,t4_i_pay,t4_e_pay,cast(t5cr as date) as t5cr,cast(t5ch as date) as t5ch,t5s,t5r,cast(t5cl as date) as t5cl,cast(t6cr as date) as t6cr,cast(t6ch as date) as t6ch,t6s,t6r,cast(t7cr as date) as t7cr,cast(t7ch as date) as t7ch,t7s,t7r,t7res1date,t7res2date,cast(t8cr as date) as t8cr,cast(t8ch as date) as t8ch,t8s,t8r,t8res1date,cast(t9cr as date) as t9cr,cast(t9ch as date) as t9ch,t9s,t9r,flag1").where("t9s='end'")
    @installrep = @installrep.where("DATE(t9ch) >= ? AND DATE(t9ch) <=?",@d1,@d2)
#    installrep
    @installrep = @installrep.where(" not cl_id=15")
    @installrep= if @staff_login.groupid.include?(2) || @staff_login.admin?
                    @installrep
                 elsif @staff_login.groupid.include?(3)
                    @installrep.where("flag='DD'")
                 elsif @staff_login.groupid.include?(6)
                    @installrep.where("flag='DT'")
                 else
                     @installrep
                 end
    if @staff_login.gr_names == ["Отдел продаж ЦД"]
        @installrep= case @staff_login.fullname
                 when /Антропов|Долгин/
                   @installrep.where(manager: ['Антропов Константин','ИП Эндер'])
                 when /Макарова/
                   @installrep.where(manager: ['Макарова Ирина','ООО "Медиа 161"','ИП Щербина','ИП Волчанская'])
                 when /Ваганов/
                   @installrep.where(manager: ['Ваганов Андрей','ИП Адаменко','ИП Долгин','АК Спецсвязь'])
                 when /Гученко/
                   @installrep.where(manager: ['Гученко Наталья','АК Спецсвязь','СТС'])
                 end
    end
    @installrep= @installrep.where(manager: @staff_login.fullname) if @staff_login.gr_names == ["Отдел продаж ДТ"]
    @installrep= if params[:flag].nil? || params[:flag].empty?
                   @installrep
                 else
                   @installrep.where(flag: params[:flag])
                 end
     @installrep= case params[:type]
                  when 'ppomap'
                    @installrep.where("type_t='ppomap'")

app/helpers/reports_helper.rb
# -*- encoding : utf-8 -*-
module ReportsHelper

  def authorize
    logger.debug "########## request.parameters[action]="+request.parameters["action"].inspect
    if !@staff_login.admin?
      case request.parameters["action"]
        when /index|new|create|services/
           true
        when /show|edit|update|destroy/
            true
        when /profitlistrep|typeconnect/
          if  @staff_login.gr_names == ["Отдел продаж ЦД"] || @staff_login.gr_names == ["Отдел продаж ДТ"]
            redirect_to clients_path, flash: { error: "Недостаточно прав" }
            false
          else
            true
          end
      end
    else
      true
    end
  end

  

  def newclient_week_collect
    [["эту неделю","/reports/newclient?dec_week=0",0],["прошлую неделю","/reports/newclient?dec_week=1",1]]
  end

  def last_comment(idtask)
    comm = Comment.where(idtask: idtask).select("text")[0]
    comm.nil? ? "" : comm.text[0..10]<<"..."
  end

  def list_phone_type_array
    ["обычный","серебряный","золотой","платиновый"]
  end
end

app/views/reports/closeakt.html.erb
  <% if flash[:error] %>
    <div id="error_explanation">
      <ul><li><%= flash[:error] %></li></ul>
    </div>
  <% end %>

<form>
<table width=100%><tr>
<td>
<b>
Клиент:
<%= select_tag :flag, options_for_select([["",""],["Цифровой Диалог","DD"],["Диалог Телеком","DT"]], params[:flag]) %>
Тип:
<%= select_tag :type, options_for_select([["",""],["ВОЛС","ppomap"],["WiFi","wifippomap"],['VoIP','voice']], params[:type]) %>
c <input type=date name=d1 value="<%=@d1%>"> по <input type=date name=d2 value="<%=@d2%>">
</td></tr><tr>
<td>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Найти", :name => nil %>
    <% rpath = reports_closeakt_path(params).split('?')
       rpath[0]+=".xls"
      %>
    <%= link_to tag("img", { :src => "/images/excel.gif", :alt => "Excel", :border=>0, :title=>"Excel"}, false), rpath.join('?') %>
</td></table>
</form>

              <table width=100% border=0  style="background-color: #f5f5dc;">
                <tr>
                <td class=hblist width= >Наименование клиента</td>
                <td class=hblist  >№ Договора</td>
                <td class=hblist  >Сервис</td>
                <td class=hblist  >Дата оплаты</td>
                <td class=hblist width= >Дата включения</td>
                <td class=hblist width= >АКТ в CRM</td>
                <td class=hblist width= >Сумма Ежемес платежа</td>
                </tr>
  <% 
logger.debug @installrep[0].inspect
   @installrep.each do |row|
        cls = cycle :sclist, :dclist
        pay_date = row.t5cr unless row.t5cr.nil?
        pay_date = row.t5ch unless row.t5ch.nil?
        pay_date = row.t5cl unless row.t5cl.nil?
        install_date = row.t7cr unless row.t7cr.nil?
        install_date = row.t7ch unless row.t7ch.nil?
        install_date = row.t7res1date unless row.t7res1date.nil?
        install_date = row.t7res2date unless row.t7res2date.nil?
        install_date = row.t8cr unless row.t8cr.nil?
        install_date = row.t8ch unless row.t8ch.nil?
        install_date = row.t8res1date unless row.t8res1date.nil?
     %>
       <tr>
<td class="<%=cls%>"><%= link_to row.cl_name, tasks_path(cl_id: row.cl_id, search: row.t_name) %></td>
<td class="<%=cls%>"><%= row.t4dog_num %></td>
<td class="<%=cls%>"><%= row.type_s %></td>
<td class="<%=cls%>"><%= pay_date  %></td>
<td class="<%=cls%>"><%= install_date %> </td>
<td class="<%=cls%>"><%= row.t9ch %> </td>
<td class="<%=cls%>"><%= row.t4_e_pay %></td>
      </tr>
  <% end %>
 </table>

app/views/reports/installrep.html.erb
  <% if flash[:error] %>
    <div id="error_explanation">
      <ul><li><%= flash[:error] %></li></ul>
    </div>
  <% end %>

<form>
<table width=100%><tr>
<td>
<b>
Клиент:
<%= select_tag :flag, options_for_select([["",""],["Цифровой Диалог","DD"],["Диалог Телеком","DT"]], params[:flag]) %>
Тип:
<%= select_tag :type, options_for_select([["",""],["ВОЛС","ppomap"],["WiFi","wifippomap"],['VoIP','voice']], params[:type]) %>
Статус:
<%= select_tag :status, options_for_select([["",""],["В процессе подключения","run"],["Сервис подан","end"]], params[:status]) %>
</td></tr><tr>
<td>
<b>Количество - <%= @installrep.count %></b></td>
<td>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Найти", :name => nil %>
    <% rpath = reports_installrep_path(params).split('?')
       rpath[0]+=".xls"
      %>
    <%= link_to tag("img", { :src => "/images/excel.gif", :alt => "Excel", :border=>0, :title=>"Excel"}, false), rpath.join('?') %>
</td></table>
</form>

              <table width=100% border=0  style="background-color: #f5f5dc;">
                <tr>
                <td class=hblist width=20%><%= sortable "cl_name", "Клиент"%></td>
                <td class=hblist width=20%><%= sortable "t_name", "Адрес"%></td>
                <td class=hblist width=10%><%= sortable "manager", "Manager"%></td>
                <td class=hblist size=10%><%= sortable "t2d", "Договор от"%></td>
                <td class=hblist size=10%><%= sortable "t5cr", "Оплата"%></td>
                <td class=hblist width=5%>Линейные работы</td>
                <td class=hblist width=5%>Сварка</td>
                <td class=hblist width=5%>Инсталляция</td>
                <td class=hblist width=5%>АКТ</td>
                <td class=hblist width=5%>Сумма инсталляции</td>
                <td class=hblist width=5%>Сумма Ежемес платежа</td>
                </tr>
  <% sumi=suma=0
   @installrep.each do |row|
        cls = cycle :sclist, :dclist
        pay_day = if row.t5cr.nil? || row.t5s != 'end'
                    nil
                  else
                    (Date.today - row.t5cr).to_i
                  end
		logger.debug row.t5cr
		logger.debug pay_day
        pay_color = if pay_day.nil?
                       cls
                    elsif pay_day > 21
                      "redlist"
                    else
                      "yellowlist"
                    end
        pay_date = row.t5cr unless row.t5cr.nil?
        pay_date = row.t5ch unless row.t5ch.nil?
        pay_date = row.t5cl unless row.t5cl.nil?
     %>
       <tr>
<td class="<%=cls%>"><%= link_to row.cl_name, tasks_path(cl_id: row.cl_id,search: row.t_name) %></td>
<td class="<%=cls%>"><%= row.t_name %></td>
<td class="<%=cls%>"><%= row.manager %></td>
<% if row.t4s=='end1' %>
  <td class="redlist">Расторжение</td>
<% else %>
  <td class="<%=cls%>"><%= row.t4dog_date unless row.t4dog_date.nil? %></td>
<% end %>
<td class="<%= pay_color%>"><%= pay_date unless pay_day.nil? %></td>
     <%
#----------------------------------  Install ----------------
      if row.type_t=='wifippomap'
        if row.t7s=='end' %>
<td class="endtd" align=center colspan=3><%=row.t7ch%></td>
     <% elsif row.t7s=='new' %>
<td class="redlist" align=center colspan=3><%=row.t7res1date%></td>
     <% elsif row.t7s=='run' %>
<td class="grlist" colspan=3><%=row.t7res1date%></td>
     <% else %>
<td class="<%=cls%>" colspan=3>&nbsp;</td>
     <% end 
      else
        if row.t7s=='end' || row.t7s=='end0' %>
<td class="endtd" align=center><%=row.t7ch%></td>
     <% elsif row.t7s=='new' %>
<td class="redlist" align=center><%=row.t7res1date%></td>
     <% elsif row.t7s=='run' %>
<td class="grlist"><%=row.t7res1date%></td>
     <% else %>
<td class="<%=cls%>">&nbsp;</td>
     <% end %>
     <% if row.t7s=='end' %>
<td class="endtd" align=center><%=row.t7ch%></td>
     <% elsif row.t7s=='new' %>
<td class="redlist" align=center><%=row.t7res2date%></td>
     <% elsif row.t7s=='run' %>
<td class="grlist"><%=row.t7res2date%></td>
     <% else %>
<td class="<%=cls%>">&nbsp;</td>
     <% end %>
     <% if row.t8s=='end' %>
<td class="endtd" align=center><%=row.t8ch%></td>
     <% elsif row.t8s=='new' %>
<td class="redlist" align=center><%=row.t8res1date%></td>
     <% elsif row.t8s=='run' %>
<td class="grlist"><%=row.t8res1date%></td>
     <% else %>
<td class="<%=cls%>">&nbsp;</td>
     <% end %>
   <% end 
#----------------------------------  END Install ----------------
%>

     <% if row.t9s=='new' %>
<td class="redlist" align=center>&nbsp;</td>
     <% elsif row.t9s=='run' %>
<td class="grlist">&nbsp;</td>
     <% else %>
<td class="<%=cls%>">&nbsp;</td>
     <% end %>

<td class="<%=cls%>"><%= row.t4_i_pay %></td>
<td class="<%=cls%>"><%= row.t4_e_pay %></td>
      </tr>
  <%
      sumi+=row.t4_i_pay.nil? ? 0 : row.t4_i_pay.to_i
      suma+=row.t4_e_pay.nil? ? 0 : row.t4_e_pay.to_i
     end %>
 <tr><td colspan=9>&nbsp;</td><td class=redlist><b><%=sumi%></b></td><td class=redlist><b><%=suma%></b></td></tr>
              </table>

app/views/reports/newclient.html.erb
  <% if flash[:error] %>
    <div id="error_explanation">
      <ul><li><%= flash[:error] %></li></ul>
    </div>
  <% end %>
<form>
<table width=100%>
<td><b>
Новые клиенты c <input type=date name=d1 value="<%=@d1%>"> по <input type=date name=d2 value="<%=@d2%>"></b>
<%= select_tag :flag, options_for_select([["",""],["Цифровой Диалог","DD"],["Диалог Телеком","DT"]], params[:flag]) %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= submit_tag "Найти", :name => nil %>
    <% rpath = reports_newclient_path(params).split('?')
       rpath[0]+=".xls"
      %>
    <%= link_to tag("img", { :src => "/images/excel.gif", :alt => "Excel", :border=>0, :title=>"Excel"}, false), rpath.join('?') %>
</td><td><%= link_to 'Добавить', new_client_path %></td></table>
</form>
<b>Количество - <%= @cl_ppo.count %></b>
<table width=100%>
  <tr>
    <td class=hblist><%= sortable "name", "Название", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist><%= sortable "address", "Адрес", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist><%= sortable "type_s", "Сервис", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist><%= sortable "target", "Скорость", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist><%= sortable "cl_src", "Источник", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist><%= sortable "manager", "Менеджер", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist><%= sortable "date_add", "Добавлен", { :d1 => @d1, :d2 => @d2, :search => params[:search], :flag => params[:flag] }%></td>
    <td class=hblist>Действия</td>
  </tr>

<% @cl_ppo.each do |client| %>
  <tr class="<%= cycle :sclist, :dclist %>">
    <td><%= link_to client.name, "/tasks/?cl_id=#{client.id}" %></td>
    <td><%= client.t_name.nil? ? client.address : client.t_name %></td>
    <td><%= client.type_s %></td>
    <td><%= client.target %></td>
    <td><%= client_source_hash[client.cl_src] %></td>
    <td><%= client.manager %></td>
    <td><%= client.date_add.strftime("%Y-%m-%d") %></td>
    <td><%= link_to tag("img", { :src => "/images/button_edit.gif", :alt => "Edit", :border=>0, :title=>"Edit"}, false), edit_client_path(client) %>
    <%= link_to tag("img", { :src => "/images/button_drop.gif", :alt => "Del", :border=>0, :title=>"Del"}, false), client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>